// <auto-generated />
namespace BlogOperations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class postimagename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(postimagename));
        
        string IMigrationMetadata.Id
        {
            get { return "201703120657129_post-image-name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
